# in Docker, it is common to base a new image on a previously-created image
FROM python:3.10-slim-buster

# Set the working directory in the image
WORKDIR /app

# install dependencies into the image - doing this first will speed up subsequent builds, as Docker will cache this step
COPY container_req.txt ./
RUN pip3 install -r container_req.txt

# the ADD command is how you add files from your local machine into a Docker image
# Copy the current directory contents into the container at /app
ADD . .

# expose the port that the Flask app is running on... by default 5000
EXPOSE 8000

# Run app.py when the container launches
CMD [ "python3", "-u", "app.py"]